apiVersion: apps/v1
kind: Deployment
metadata:
  name: pihole
spec:
  selector:
    matchLabels:
      app: pihole
  template:
    metadata:
      labels:
        app: pihole
    spec:
      containers:
      - name: pihole
        image: pihole/pihole:latest
        env:
        - name: TZ
          value: "Europe/Madrid"
        - name: WEBPASSWORD
          value: "Alu-in2a"
        - name: DNS1
          value: "1.1.1.1"
        - name: DNS2
          value: "8.8.8.8"
        - name: WEB_PORT
          value: "80"
        ports:
        - containerPort: 53
          protocol: UDP
        - containerPort: 80
          protocol: TCP
        - containerPort: 443
          protocol: TCP
        volumeMounts:
        - name: pihole-config
          mountPath: "/pi-hole/config"
        - name: dnsmasq-config
          mountPath: "/pi-hole/dnsmasq"
      volumes:
      - name: pihole-config
        persistentVolumeClaim:
          claimName: pihole-config-pvc  # Requiere un PVC previamente creado
      - name: dnsmasq-config
        persistentVolumeClaim:
          claimName: dnsmasq-config-pvc  # Requiere un PVC previamente creado
