apiVersion: v1
kind: Service
metadata:
  name: pihole
spec:
  type: NodePort
  selector:
    app: pihole
  ports:
  - name: dns-udp
    port: 53
    targetPort: 53
    protocol: UDP
    nodePort: 30053
  - name: dns-tcp
    port: 53
    targetPort: 53
    protocol: TCP
    nodePort: 30053
  - name: web-http
    port: 80
    targetPort: 80
    protocol: TCP
    nodePort: 30080
  - name: web-https
    port: 443
    targetPort: 443
    protocol: TCP
    nodePort: 30443
